float:
  any:
  - base_args: ['@metric', '@dimension']
    constructor: vdb
    disabled: false
    docker_tag: ann-benchmarks-vdb
    module: ann_benchmarks.algorithms.vdb
    name: vdb
    run_groups:
      HNSW:
        args:
          M: [16]
          efConstruction: 500
        query_args: [[10, 15, 20, 25, 30, 35, 40, 50, 60, 80, 120, 200, 400, 600,
            800]]
